name: Python

on:
  push:
    paths:
      - 'applications/generate/**'
  pull_request:
    paths:
      - 'applications/generate/**'

jobs:
  python:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    steps:
      - name: Check out GitHub repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install development dependencies
        run: pip install -r requirements.txt
        working-directory: ./applications/generate
      - name: Run type check
        run: mypy philadelphia
        working-directory: ./applications/generate
